CREATE INDEX "attachments_project_id_idx" ON "attachments" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "attachments_owner_idx" ON "attachments" USING btree ("owner_type","owner_id");--> statement-breakpoint
CREATE INDEX "cost_codes_project_id_idx" ON "cost_codes" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "locations_project_id_idx" ON "locations" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "project_companies_project_id_idx" ON "project_companies" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "project_users_user_id_idx" ON "project_users" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "specifications_sections_project_id_idx" ON "specifications_sections" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "document_folders_project_id_idx" ON "document_folders" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "documents_project_id_idx" ON "documents" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "documents_folder_id_idx" ON "documents" USING btree ("folder_id");--> statement-breakpoint
CREATE INDEX "drawing_revisions_drawing_id_idx" ON "drawing_revisions" USING btree ("drawing_id");--> statement-breakpoint
CREATE INDEX "drawings_project_id_idx" ON "drawings" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "markups_drawing_revision_id_idx" ON "markups" USING btree ("drawing_revision_id");--> statement-breakpoint
CREATE INDEX "rfi_distribution_rfi_id_idx" ON "rfi_distribution" USING btree ("rfi_id");--> statement-breakpoint
CREATE INDEX "rfi_responses_rfi_id_idx" ON "rfi_responses" USING btree ("rfi_id");--> statement-breakpoint
CREATE INDEX "rfis_project_id_idx" ON "rfis" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "submittal_packages_submittal_id_idx" ON "submittal_packages" USING btree ("submittal_id");--> statement-breakpoint
CREATE INDEX "submittal_reviews_revision_id_idx" ON "submittal_reviews" USING btree ("revision_id");--> statement-breakpoint
CREATE INDEX "submittal_revisions_package_id_idx" ON "submittal_revisions" USING btree ("package_id");--> statement-breakpoint
CREATE INDEX "submittals_project_id_idx" ON "submittals" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "submittals_ball_in_court_user_idx" ON "submittals" USING btree ("ball_in_court_user_id");--> statement-breakpoint
CREATE INDEX "daily_log_delays_daily_log_id_idx" ON "daily_log_delays" USING btree ("daily_log_id");--> statement-breakpoint
CREATE INDEX "daily_log_deliveries_daily_log_id_idx" ON "daily_log_deliveries" USING btree ("daily_log_id");--> statement-breakpoint
CREATE INDEX "daily_log_equipment_daily_log_id_idx" ON "daily_log_equipment" USING btree ("daily_log_id");--> statement-breakpoint
CREATE INDEX "daily_log_manpower_daily_log_id_idx" ON "daily_log_manpower" USING btree ("daily_log_id");--> statement-breakpoint
CREATE INDEX "daily_log_safety_incidents_daily_log_id_idx" ON "daily_log_safety_incidents" USING btree ("daily_log_id");--> statement-breakpoint
CREATE INDEX "punch_item_history_punch_item_id_idx" ON "punch_item_history" USING btree ("punch_item_id");--> statement-breakpoint
CREATE INDEX "punch_items_project_id_idx" ON "punch_items" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "punch_items_assignee_user_id_idx" ON "punch_items" USING btree ("assignee_user_id");--> statement-breakpoint
CREATE INDEX "photo_albums_project_id_idx" ON "photo_albums" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "photos_project_id_idx" ON "photos" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "photos_album_id_idx" ON "photos" USING btree ("album_id");--> statement-breakpoint
CREATE INDEX "checklist_template_items_template_id_idx" ON "checklist_template_items" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX "checklist_templates_project_id_idx" ON "checklist_templates" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "inspection_responses_inspection_id_idx" ON "inspection_responses" USING btree ("inspection_id");--> statement-breakpoint
CREATE INDEX "inspections_project_id_idx" ON "inspections" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "budget_line_items_project_id_idx" ON "budget_line_items" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "change_events_project_id_idx" ON "change_events" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "change_orders_project_id_idx" ON "change_orders" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "change_orders_target_idx" ON "change_orders" USING btree ("target_type","target_id");--> statement-breakpoint
CREATE INDEX "commitment_line_items_commitment_id_idx" ON "commitment_line_items" USING btree ("commitment_id");--> statement-breakpoint
CREATE INDEX "commitments_project_id_idx" ON "commitments" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "meeting_items_meeting_id_idx" ON "meeting_items" USING btree ("meeting_id");--> statement-breakpoint
CREATE INDEX "meetings_project_id_idx" ON "meetings" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "payment_application_lines_payment_application_id_idx" ON "payment_application_lines" USING btree ("payment_application_id");--> statement-breakpoint
CREATE INDEX "payment_application_lines_sov_line_id_idx" ON "payment_application_lines" USING btree ("sov_line_id");--> statement-breakpoint
CREATE INDEX "payment_applications_project_id_idx" ON "payment_applications" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "payment_applications_commitment_id_idx" ON "payment_applications" USING btree ("commitment_id");--> statement-breakpoint
CREATE INDEX "potential_change_orders_change_event_id_idx" ON "potential_change_orders" USING btree ("change_event_id");