import type { Module } from "../constants/modules";
import type { PermissionLevel } from "../constants/permission-levels";
import type { ProjectRole } from "../constants/roles";
import type { ModuleLevels } from "./engine";

/**
 * Default permission_templates bundle per role. Seeded once (packages/db
 * seed script) and assignable per project_user; per-user overrides
 * (project_user_permissions) still win over these (see engine.ts). This is
 * a starting matrix, not a contractual spec — revisit per-role defaults as
 * real usage surfaces gaps (docs/DATA_MODEL.md §13 open items).
 */
export const DEFAULT_ROLE_TEMPLATE_LEVELS: Record<ProjectRole, ModuleLevels> = {
  owner_admin: allModulesAt("admin"),
  project_manager: {
    directory: "admin",
    documents: "admin",
    drawings: "admin",
    rfis: "admin",
    submittals: "admin",
    daily_log: "admin",
    punch_list: "admin",
    photos: "admin",
    inspections: "admin",
    budget: "admin",
    commitments: "admin",
    change_management: "admin",
    progress_billing: "admin",
    meetings: "admin",
    schedule: "admin",
    safety: "standard",
    tm_tickets: "standard",
    reports: "admin",
    correspondence: "admin",
    prime_contract: "admin",
    direct_costs: "admin",
    prequalification: "admin",
    bidding: "admin",
    estimating: "admin",
  },
  project_engineer: {
    directory: "read",
    documents: "standard",
    drawings: "standard",
    rfis: "standard",
    submittals: "standard",
    daily_log: "standard",
    punch_list: "standard",
    photos: "standard",
    inspections: "standard",
    budget: "read",
    commitments: "read",
    change_management: "read",
    progress_billing: "read",
    meetings: "standard",
    schedule: "standard",
    safety: "read",
    tm_tickets: "read",
    reports: "read",
    correspondence: "standard",
    prime_contract: "read",
    direct_costs: "read",
    prequalification: "read",
    bidding: "read",
    estimating: "read",
  },
  superintendent: {
    directory: "read",
    documents: "read",
    drawings: "read",
    rfis: "read",
    submittals: "read",
    daily_log: "admin",
    punch_list: "admin",
    photos: "standard",
    inspections: "standard",
    budget: "none",
    commitments: "none",
    change_management: "none",
    progress_billing: "none",
    meetings: "standard",
    schedule: "read",
    safety: "standard",
    tm_tickets: "standard",
    reports: "read",
    correspondence: "read",
    prime_contract: "none",
    direct_costs: "none",
    prequalification: "none",
    bidding: "none",
    estimating: "none",
  },
  foreman: {
    directory: "none",
    documents: "read",
    drawings: "read",
    rfis: "none",
    submittals: "none",
    daily_log: "standard",
    punch_list: "standard",
    photos: "standard",
    inspections: "read",
    budget: "none",
    commitments: "none",
    change_management: "none",
    progress_billing: "none",
    meetings: "none",
    schedule: "read",
    safety: "standard",
    tm_tickets: "standard",
    reports: "none",
    correspondence: "none",
    prime_contract: "none",
    direct_costs: "none",
    prequalification: "none",
    bidding: "none",
    estimating: "none",
  },
  qa_qc: {
    directory: "read",
    documents: "standard",
    drawings: "standard",
    rfis: "read",
    submittals: "read",
    daily_log: "read",
    punch_list: "admin",
    photos: "standard",
    inspections: "admin",
    budget: "none",
    commitments: "none",
    change_management: "none",
    progress_billing: "none",
    meetings: "read",
    schedule: "read",
    safety: "read",
    tm_tickets: "none",
    reports: "read",
    correspondence: "read",
    prime_contract: "none",
    direct_costs: "none",
    prequalification: "none",
    bidding: "none",
    estimating: "none",
  },
  safety_officer: {
    directory: "read",
    documents: "read",
    drawings: "read",
    rfis: "none",
    submittals: "none",
    daily_log: "standard",
    punch_list: "read",
    photos: "standard",
    inspections: "standard",
    budget: "none",
    commitments: "none",
    change_management: "none",
    progress_billing: "none",
    meetings: "read",
    schedule: "read",
    safety: "admin",
    tm_tickets: "none",
    reports: "read",
    correspondence: "none",
    prime_contract: "none",
    direct_costs: "none",
    prequalification: "none",
    bidding: "none",
    estimating: "none",
  },
  subcontractor: {
    directory: "none",
    documents: "read",
    drawings: "read",
    rfis: "standard",
    submittals: "standard",
    daily_log: "read",
    punch_list: "standard",
    photos: "standard",
    inspections: "read",
    budget: "none",
    commitments: "none",
    change_management: "none",
    progress_billing: "none",
    meetings: "read",
    schedule: "read",
    safety: "read",
    tm_tickets: "standard",
    reports: "none",
    correspondence: "read",
    prime_contract: "none",
    direct_costs: "none",
    prequalification: "none",
    bidding: "none",
    estimating: "none",
  },
  consultant: {
    directory: "read",
    documents: "standard",
    drawings: "standard",
    rfis: "standard",
    submittals: "standard",
    daily_log: "read",
    punch_list: "read",
    photos: "read",
    inspections: "standard",
    budget: "none",
    commitments: "none",
    change_management: "none",
    progress_billing: "none",
    meetings: "read",
    schedule: "read",
    safety: "read",
    tm_tickets: "none",
    reports: "read",
    correspondence: "read",
    prime_contract: "none",
    direct_costs: "none",
    prequalification: "none",
    bidding: "none",
    estimating: "none",
  },
  client_viewer: {
    directory: "read",
    documents: "read",
    drawings: "read",
    rfis: "read",
    submittals: "read",
    daily_log: "read",
    punch_list: "read",
    photos: "read",
    inspections: "read",
    // Forced to "none" regardless of this value by the permission engine
    // and RLS (docs/DATA_MODEL.md §10) — set explicitly here for clarity.
    budget: "none",
    commitments: "none",
    change_management: "none",
    progress_billing: "none",
    meetings: "read",
    schedule: "read",
    safety: "read",
    tm_tickets: "none",
    reports: "read",
    correspondence: "read",
    prime_contract: "none",
    direct_costs: "none",
    prequalification: "none",
    bidding: "none",
    estimating: "none",
  },
};

/** Naming convention shared by the seed script (which creates these rows) and invite acceptance (which looks one up by role to default a new member's permission_templates assignment). */
export function defaultTemplateNameForRole(role: ProjectRole): string {
  return `Default — ${role}`;
}

function allModulesAt(level: PermissionLevel): Record<Module, PermissionLevel> {
  const modules: Module[] = [
    "directory",
    "documents",
    "drawings",
    "rfis",
    "submittals",
    "daily_log",
    "punch_list",
    "photos",
    "inspections",
    "budget",
    "commitments",
    "change_management",
    "progress_billing",
    "meetings",
    "schedule",
    "safety",
    "tm_tickets",
    "reports",
    "correspondence",
    "prime_contract",
    "direct_costs",
    "prequalification",
    "bidding",
    "estimating",
  ];
  return Object.fromEntries(modules.map((m) => [m, level])) as Record<Module, PermissionLevel>;
}
